// ============================================
// RENTECH PROPERTIES - PROPERTIES DATABASE
// All property data for the platform
// ============================================

const PROPERTIES_DB = [
    {
        id: 1,
        title: "Modern 2BR Apartment",
        area: "Kilimani",
        price: 65000,
        beds: 2,
        baths: 1,
        size: 85,
        type: "2BR",
        furnished: true,
        badge: "Featured",
        status: "Available Now",
        emoji: "🏢",
        amenities: ["Security", "Parking", "Generator", "CCTV"],
        desc: "Spacious 2-bedroom in heart of Kilimani. Walking distance to Yaya Centre. All-day water, backup generator.",
        matatu: "Near Yaya Centre stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80"
    },
    {
        id: 2,
        title: "Executive Studio",
        area: "Westlands",
        price: 35000,
        beds: 1,
        baths: 1,
        size: 45,
        type: "Studio",
        furnished: true,
        badge: "New",
        status: "Available Now",
        emoji: "🏙️",
        amenities: ["Borehole", "Security", "Lift", "CCTV"],
        desc: "Well-maintained studio with city views. Near Sarit Centre and major banks.",
        matatu: "Near Westlands stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80"
    },
    {
        id: 3,
        title: "Affordable Bedsitter",
        area: "Kasarani",
        price: 12000,
        beds: 1,
        baths: 1,
        size: 25,
        type: "Bedsitter",
        furnished: false,
        badge: "",
        status: "Available Now",
        emoji: "🏠",
        amenities: ["Parking", "Borehole"],
        desc: "Clean bedsitter near Kasarani Stadium. Reliable water. Ideal for students.",
        matatu: "Near Kasarani stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80"
    },
    {
        id: 4,
        title: "3BR Family Maisonette",
        area: "Lang'ata",
        price: 85000,
        beds: 3,
        baths: 2,
        size: 140,
        type: "Maisonette",
        furnished: false,
        badge: "Featured",
        status: "Available Now",
        emoji: "🏡",
        amenities: ["DSQ", "Security", "Parking", "Generator"],
        desc: "Spacious 3-bedroom maisonette with DSQ. Quiet estate, great schools nearby.",
        matatu: "Near Lang'ata road",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80"
    },
    {
        id: 5,
        title: "1BR South B Apartment",
        area: "South B",
        price: 28000,
        beds: 1,
        baths: 1,
        size: 55,
        type: "1BR",
        furnished: false,
        badge: "New",
        status: "Available Now",
        emoji: "🏢",
        amenities: ["Lift", "Security", "Parking"],
        desc: "Newly renovated 1-bedroom. Easy CBD access via Mombasa Road.",
        matatu: "Mombasa Road stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80"
    },
    {
        id: 6,
        title: "Luxury Furnished Studio",
        area: "Lavington",
        price: 55000,
        beds: 1,
        baths: 1,
        size: 50,
        type: "Studio",
        furnished: true,
        badge: "",
        status: "Available Now",
        emoji: "✨",
        amenities: ["Pool", "Gym", "Security", "Parking", "CCTV"],
        desc: "Executive studio in Lavington. Shared pool, gym, 24hr security. Perfect for expats.",
        matatu: "Lavington Mall stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1630699144339-420f59b4747a?w=600&q=80"
    },
    {
        id: 7,
        title: "Budget Bedsitter",
        area: "Eastleigh",
        price: 8000,
        beds: 1,
        baths: 1,
        size: 20,
        type: "Bedsitter",
        furnished: false,
        badge: "",
        status: "Available Now",
        emoji: "🏠",
        amenities: ["Security", "Borehole"],
        desc: "Affordable, clean bedsitter in Eastleigh. Close to city centre. Good transport.",
        matatu: "Eastleigh 1st Avenue",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80"
    },
    {
        id: 8,
        title: "Premium 3BR Apartment",
        area: "Westlands",
        price: 120000,
        beds: 3,
        baths: 2,
        size: 165,
        type: "3BR",
        furnished: true,
        badge: "Featured",
        status: "Available Now",
        emoji: "🌟",
        amenities: ["Pool", "Gym", "Security", "Parking", "Generator", "Lift"],
        desc: "Ultra-modern 3-bedroom. Rooftop pool, gym, stunning views. Best in Westlands.",
        matatu: "Westlands roundabout",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80"
    },
    {
        id: 9,
        title: "New 2BR Kasarani",
        area: "Kasarani",
        price: 22000,
        beds: 2,
        baths: 1,
        size: 70,
        type: "2BR",
        furnished: false,
        badge: "New",
        status: "Available Now",
        emoji: "🏗️",
        amenities: ["Parking", "Borehole", "Security"],
        desc: "Newly completed 2-bedroom. Tiled throughout, reliable water supply.",
        matatu: "Kasarani stadium stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=600&q=80"
    },
    {
        id: 10,
        title: "Garden View 1BR",
        area: "Karen",
        price: 75000,
        beds: 1,
        baths: 1,
        size: 65,
        type: "1BR",
        furnished: true,
        badge: "",
        status: "Available Now",
        emoji: "🌿",
        amenities: ["Garden", "Security", "Parking", "Borehole"],
        desc: "Serene 1-bedroom with private garden in Karen. Peace within Nairobi.",
        matatu: "Karen shopping centre",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600&q=80"
    },
    {
        id: 11,
        title: "Studio Near South C",
        area: "South C",
        price: 18000,
        beds: 1,
        baths: 1,
        size: 35,
        type: "Studio",
        furnished: false,
        badge: "New",
        status: "Available Now",
        emoji: "🏙️",
        amenities: ["Security", "Borehole", "Parking"],
        desc: "Modern studio in South C. Close to Nairobi CBD and Industrial Area.",
        matatu: "South C stage",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80"
    },
    {
        id: 12,
        title: "4BR Executive Home",
        area: "Karen",
        price: 180000,
        beds: 4,
        baths: 3,
        size: 250,
        type: "4BR+",
        furnished: true,
        badge: "Featured",
        status: "Available Now",
        emoji: "🏰",
        amenities: ["Pool", "Garden", "DSQ", "Security", "Generator", "Gym"],
        desc: "Luxurious 4-bedroom Karen home with pool, DSQ, lush garden. Executive living.",
        matatu: "Hardy stage Karen",
        verified: true,
        inspected: true,
        img: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80"
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PROPERTIES_DB;
}